### ISSUE TITLE
Extra warning : wrong header protection name / header instructions

### ISSUE THREAD

**Issue by kalunik** [skrtks/norminette#8]
**Describe the bug**
Warning in header from plugin : 
`Norminette: Wrong header protection name`,
`Norminette: Header protection must include all the instructions`.
But Norminette in terminal say it is OK!

**To Reproduce**
1. Create a new `test.h`
2. Add to your `test.h` :

`#ifndef TEST_H`
`# define TEST_H`

3. Then add any function prototype. For me it would be:

`void	push_swap(int argc, char **argv)`

4. At the end of header don't forget:

`#endif`

5. You'll see two warning on `#ifndef` and `# define`

**Expected behavior**
I expected that it would be no problem, but plugin said about two problems.
 
**Screenshots**

<img width="692" alt="Screen Shot 2021-09-24 at 4 43 45 PM" src="https://user-images.githubusercontent.com/33860048/134684585-37ba2828-fa27-46fe-b7f8-2c15031e58d5.png">

**System info :**
 - Plugin version : 0.1.0
 - Clion : 2021.2.2
 - OS : macOS 10.14.6

**Comment by skrtks** [comment]
Hi! Thanks for reporting this. I run Norminette on a temporary file because CLion works with a virtual document and doesn't save changes to the file system right away. The error was showing because Norminette expected the header guard to have the same name as the temp file… It should be fixed now (usually takes 1 or 2 days for the update to be approved).

**Comment by skrtks** [comment]
Please let me know if you're still having problems after updating. If not, you can close the issue 👍🏽
